[package]
name = "nanite"
version = "1.0.0"
authors = ["Kurtis Rainbolt-Greene <kurtis@rainbolt-greene.online>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
